# Generated by Django 5.1.3 on 2025-01-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at_task_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrption',
            new_name='description',
        ),
    ]
